<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

// Predicates.
define('ISLANDORA_MANUSCRIPT_HAS_TRANSFORM_PREDICATE', 'hasTransform');
define('ISLANDORA_MANUSCRIPT_HAS_EAD_PREDICATE', 'isMemberOf');

// Islandora Objects.
define('ISLANDORA_MANUSCRIPT_DEFAULT_TRANSFORM', 'islandora:defaultTransform');

/**
 * Implements hook_menu().
 */
function islandora_manuscript_menu() {
  return array(
    'admin/islandora/solution_pack_config/manuscript' => array(
      'title' => 'Manuscript Solution Pack',
      'description' => 'Configure the Manuscript Solution Pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_manuscript_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora/object/%islandora_object/manuscript/manuscripts' => array(
      'title' => 'Manuscripts',
      'page callback' => 'islandora_manuscript_list_manuscripts',
      'page arguments' => array(2),
      'access callback' => 'islandora_user_access',
      'access arguments' => array(
        2, array(ISLANDORA_VIEW_OBJECTS), array('islandora:findingAidCModel'),
      ),
      'file' => 'includes/manuscript_list.inc',
      'type' => MENU_LOCAL_TASK,
    ),
    'islandora/object/%islandora_object/manuscript/pages' => array(
      'title' => 'Pages',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_manuscript_pages_menu',
      'page arguments' => array(2),
      'access callback' => 'islandora_user_access',
      'access arguments' => array(
        2, array(ISLANDORA_VIEW_OBJECTS), array('islandora:manuscriptCModel'),
      ),
    ),
    'islandora/object/%islandora_object/manage/tei_transform' => array(
      'title' => 'TEI Transform',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'islandora_manuscript_tei_transform_form',
        2,
      ),
      'access callback' => 'islandora_user_access',
      'access arguments' => array(
        2,
        array(ISLANDORA_MANAGE_PROPERTIES),
        array(
          'islandora:findingAidCModel',
          'islandora:collectionCModel',
        ),
      ),
      'file' => 'includes/associate_transform.form.inc',
    ),
    'islandora/object/%islandora_object/manage/manuscript' => array(
      'title' => 'Manuscript',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_paged_content_manage_pages_menu',
      'page arguments' => array(2),
      'access callback' => 'islandora_paged_content_manage_pages_access_callback',
      'access arguments' => array(2, array('islandora:manuscriptCModel')),
      'file path' => drupal_get_path('module', 'islandora_paged_content'),
      'file' => 'includes/manage_pages.inc',
    ),
    'islandora/object/%islandora_object/manage/manuscript/ingest' => array(
      'title' => 'Add Page',
      'page callback' => 'islandora_manuscript_ingest_page',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_ACTION,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_INGEST, 2),
      'file' => 'includes/manage_manuscript.inc',
    ),
    'islandora/object/%islandora_object/manage/manuscript/ingest_zipped' => array(
      'title' => 'Add Zipped Pages',
      'page callback' => 'islandora_paged_content_ingest_zipped_pages',
      'page arguments' => array(2,
        array('tif', 'tiff', 'jpg', 'jpeg', 'jp2'),
        'islandora:manuscriptPageCModel',
        variable_get('islandora_manuscript_ingest_derivatives', array('ocr')),
      ),
      'type' => MENU_LOCAL_ACTION,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_INGEST, 2),
      'file path' => drupal_get_path('module', 'islandora_paged_content'),
      'file' => 'includes/manage_pages.inc',
    ),
    'islandora/object/%islandora_object/manage/manuscript/link-finding-aid' => array(
      'title' => 'Link with Finding Aid',
      'type' => MENU_LOCAL_ACTION,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_manuscript_link_to_finding_aid_form', 2),
      'access callback' => 'islandora_manuscript_link_to_finding_aid_access_callback',
      'access arguments' => array(2),
      'file' => 'includes/link.inc',
    ),
    'islandora/object/%islandora_object/manage/manuscript_page' => array(
      'title' => 'Page',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_paged_content_manage_page_menu',
      'page arguments' => array(2),
      'access callback' => 'islandora_paged_content_manage_page_access_callback',
      'access arguments' => array(2, array('islandora:manuscriptPageCModel')),
      'file path' => drupal_get_path('module', 'islandora_paged_content'),
      'file' => 'includes/manage_page.inc',
    ),
    'islandora/manuscript/autocomplete/finding_aid/%menu_tail' => array(
      'title' => 'Finding Aid Autocomplete Callback',
      'page callback' => 'islandora_manuscript_autocomplete_finding_aid',
      'page arguments' => array(4),
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
      'load arguments' => array('%map', '%index'),
      'file' => 'includes/link.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/object/%islandora_object/manage/overview/islandora_manuscript_ingest' => array(
      'title' => 'Add a manuscript',
      'page callback' => 'islandora_manuscript_manuscript_ingest',
      'page arguments' => array(2),
      'access callback' => 'islandora_manuscript_manuscript_ingest_access_callback',
      'access arguments' => array(2),
      'file' => 'includes/link.inc',
      'type' => MENU_LOCAL_ACTION,
    ),
  );
}

/**
 * Access callback for finding aid link path.
 */
function islandora_manuscript_link_to_finding_aid_access_callback($object) {
  module_load_include('inc', 'islandora_manuscript', 'includes/link');
  return $object instanceof AbstractObject && islandora_datastream_access(ISLANDORA_METADATA_EDIT, $object['RELS-EXT']);
}

/**
 * Manuscript ingest access callback.
 */
function islandora_manuscript_manuscript_ingest_access_callback($object) {
  return $object instanceof AbstractObject && in_array('islandora:findingAidCModel', $object->models) && islandora_object_access(ISLANDORA_INGEST, $object);
}

/**
 * Renders the Pages local menu task.
 *
 * @param AbstractObject $object
 *   The book object to fetch the pages from.
 *
 * @return string
 *   The HTML representation of the given books pages.
 */
function islandora_manuscript_pages_menu(AbstractObject $object) {
  module_load_include('inc', 'islandora', 'includes/breadcrumb');
  drupal_set_breadcrumb(islandora_get_breadcrumbs($object));
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  $pages = islandora_paged_content_get_pages($object);
  return theme('islandora_objects', array('objects' => array_keys($pages)));
}

/**
 * Implements hook_theme().
 */
function islandora_manuscript_theme() {
  return array(
    'islandora_manuscript_manuscript' => array(
      'variables' => array(
        'object' => NULL,
        'viewer_wrapper_attributes' => array(
          'id' => 'manuscript-viewer',
        ),
      ),
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-manuscript-manuscript',
    ),
    'islandora_manuscript_page' => array(
      'variables' => array('object' => NULL),
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-manuscript-page',
    ),
    'islandora_manuscript_ead_display' => array(
      'variables' => array(
        'object' => NULL,
        'xslt_parameters' => array(),
        'xslt_functions' => array(
          'islandora_manuscript_build_parented_query_url',
          'islandora_manuscript_build_flat_query_url',
        ),
        'doc' => NULL,
        'xslt_doc' => NULL,
      ),
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-manuscript-ead-display',
    ),
    'islandora_manuscript_ead_display_failure' => array(
      'variables' => array(
        'object' => NULL,
      ),
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-manuscript-ead-display-failure',
    ),

  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_manuscript_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_manuscript');
  // Convenience Method to construct an object.
  $create_object = function (IslandoraTuque $connection, array $args) {
    $object = $connection->repository->constructObject($args['pid']);
    $object->owner = 'fedoraAdmin';
    $object->label = $args['label'];
    foreach ($args['datastreams'] as $dsid => $properties) {
      $control_group = isset($properties['control_group']) ? $properties['control_group'] : 'M';
      $datastream = $object->constructDatastream($dsid, $control_group);
      $datastream->label = isset($properties['label']) ? $properties['label'] : $dsid;
      $datastream->mimetype = isset($properties['mimetype']) ? $properties['mimetype'] : 'text/xml';
      $datastream->setContentFromFile($properties['file'], FALSE);
      $object->ingestDatastream($datastream);
    }
    // We must set the model after the datastreams as Tuque will ignore the
    // RELS-EXT content if the model is set first.
    if (isset($args['model'])) {
      $object->models = $args['model'];
    }
    return $object;
  };
  // Finding Aid Content Model.
  $manuscript_finding_aid_content_model = $create_object($connection, array(
    'pid' => 'islandora:findingAidCModel',
    'label' => 'Finding Aid Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/manuscript_finding_aid_ds_composite_model.xml",
      ),
    ),
  ));
  // Manuscript Content Model.
  $manuscript_content_model = $create_object($connection, array(
    'pid' => 'islandora:manuscriptCModel',
    'label' => 'Manuscript Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/manuscript_ds_composite_model.xml",
      ),
    ),
  ));
  // Manuscript Page Content Model.
  $manuscript_page_content_model = $create_object($connection, array(
    'pid' => 'islandora:manuscriptPageCModel',
    'label' => 'Manuscript Page Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => drupal_get_path('module', 'islandora_paged_content') . '/xml/islandora_pageCModel_ds_composite_model.xml',
      ),
    ),
  ));
  // Transform Content Model.
  $transform_content_model = $create_object($connection, array(
    'pid' => 'islandora:transformCModel',
    'label' => 'Transform Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/transform_ds_composite_model.xml",
      ),
    ),
  ));
  // Manuscript / Finding Aid Collection.
  $manuscript_collection = $create_object($connection, array(
    'pid' => 'islandora:manuscriptCollection',
    'label' => 'Manuscript Collection',
    'model' => 'islandora:collectionCModel',
    'datastreams' => array(
      'TN' => array(
        'file' => "$module_path/images/folder.png",
        'mimetype' => 'image/png',
      ),
      'COLLECTION_POLICY' => array(
        'file' => "$module_path/data/objects/manuscript_collection_policy.xml",
      ),
    ),
  ));
  $manuscript_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Transform Collection.
  $transform_collection = $create_object($connection, array(
    'pid' => 'islandora:transformCollection',
    'label' => 'Transform Collection',
    'model' => 'islandora:collectionCModel',
    'datastreams' => array(
      'TN' => array(
        'file' => "$module_path/images/folder.png",
        'mimetype' => 'image/png',
      ),
      'COLLECTION_POLICY' => array(
        'file' => "$module_path/data/objects/transform_collection_policy.xml",
      ),
    ),
  ));
  $transform_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Default transform.
  $default_transform = $create_object($connection, array(
    'pid' => ISLANDORA_MANUSCRIPT_DEFAULT_TRANSFORM,
    'label' => 'Default Transform',
    'model' => 'islandora:transformCModel',
    'datastreams' => array(
      'XSLT' => array(
        'file' => "$module_path/data/objects/default_transform.xsl",
        'mimetype' => 'application/xslt+xml',
      ),
    ),
  ));
  return array(
    'islandora_manuscript' => array(
      'title' => 'Islandora Manuscript Solution Pack',
      'objects' => array(
        $manuscript_finding_aid_content_model,
        $manuscript_content_model,
        $manuscript_page_content_model,
        $transform_content_model,
        $manuscript_collection,
        $transform_collection,
        $default_transform,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_findingaidcmodel_islandora_ingest_steps() {
  return array(
    'islandora_manuscript_ead_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_manuscript_ead_upload_form',
      'module' => 'islandora_manuscript',
      'file' => 'includes/ead_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_manuscriptcmodel_islandora_ingest_steps($form_state) {
  $steps = array(
    'islandora_manuscript_tei_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_manuscript_tei_upload_form',
      'module' => 'islandora_manuscript',
      'file' => 'includes/tei_upload.form.inc',
    ),
  );

  $steps['islandora_manuscript_link_to_finding_aid'] = array(
    'weight' => 5,
    'type' => 'form',
    'form_id' => 'islandora_manuscript_link_to_finding_aid_form',
    'module' => 'islandora_manuscript',
    'file' => 'includes/link.inc',
  );

  return $steps;
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_transformcmodel_islandora_ingest_steps() {
  return array(
    'islandora_manuscript_transform_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_manuscript_transform_upload_form',
      'module' => 'islandora_manuscript',
      'file' => 'includes/transform_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_xml_form_builder_get_transforms().
 *
 * No default form is defined for EAD, but if someone should add one they can
 * use this transform.
 */
function islandora_manuscript_xml_form_builder_get_transforms() {
  $module_path = drupal_get_path('module', 'islandora_manuscript');
  return array(
    'ead_to_dc.xsl' => "{$module_path}/data/transforms/ead_to_dc.xsl",
  );
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_manuscript_xml_form_builder_form_associations() {
  return array(
    'islandora_manuscript_mods_form' => array(
      'content_model' => 'islandora:manuscriptCModel',
      'form_name' => 'Manuscript MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_manuscript_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_manuscript');
  return array(
    'Manuscript MODS form' => array(
      'form_file' => "$module_path/data/forms/islandora_manuscript_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_manuscriptpagecmodel_islandora_ingest_steps(array $form_state) {
  $shared_storage = islandora_ingest_form_get_shared_storage($form_state);
  if (empty($shared_storage['manuscript'])) {
    return;
  }
  return array(
    'islandora_manuscript_upload_pages' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_paged_content_upload_page_form',
      'args' => array($shared_storage['manuscript']),
      'module' => 'islandora_paged_content',
      'file' => 'includes/upload_page.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_derivative().
 */
function islandora_manuscript_islandora_manuscriptcmodel_islandora_derivative() {
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  return islandora_paged_content_paged_object_derivatives('islandora_manuscript');
}

/**
 * Implements hook_islandora_derivative().
 */
function islandora_manuscript_islandora_manuscriptpagecmodel_islandora_derivative() {
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  return islandora_paged_content_page_derivatives('islandora_manuscript');
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_manuscript_islandora_manuscriptcmodel_islandora_view_object($object) {
  $output = theme('islandora_manuscript_manuscript', array('object' => $object));
  return array('islandora_manuscript' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_manuscript_islandora_findingaidcmodel_islandora_view_object($object) {
  return array(
    'islandora_manuscript_ead_display' => array(
      '#type' => 'markup',
      '#theme' => 'islandora_manuscript_ead_display',
      '#object' => $object,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_manuscript_islandora_manuscriptpagecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_manuscript_page', array('object' => $object));
  return array('islandora_manuscript' => $output);
}

/**
 * Implements hook_form_FORM_ID_form_alter().
 */
function islandora_manuscript_form_islandora_delete_object_form_alter(array &$form, array &$form_state) {
  form_load_include($form_state, 'inc', 'islandora_manuscript', 'includes/delete.form');
  $object = $form_state['object'];
  if (in_array('islandora:transformCModel', $object->models)) {
    $form['#submit'] = array('islandora_manuscript_islandora_delete_object_form_submit');
  }
}

/**
 * Implements hook_file_mimetype_mapping_alter().
 */
function islandora_manuscript_file_mimetype_mapping_alter(&$mapping) {
  $mime_detect = new MimeDetect();
  $types = $mime_detect->getMimeTypes();
  $intersect = array_intersect_key($types, $mapping['extensions']);
  foreach ($intersect as $ext => $mime) {
    $keys = array_keys($mapping['mimetypes'], $mime);
    if (empty($keys)) {
      $mapping['mimetypes'][] = $mime;
      $keys = array_keys($mapping['mimetypes'], $mime);
    }
    $mapping['extensions'][$ext] = reset($keys);
  }
}

/**
 * Implements hook_block_info().
 */
function islandora_manuscript_block_info() {
  return array(
    'container_list' => array(
      'info' => t('Islandora Manuscript Container List'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_manuscript_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'container_list':
      if (strpos(current_path(), 'islandora/object') === 0) {
        $object = menu_get_object('islandora_object', 2);
        if ($object) {
          if (!in_array('islandora:findingAidCModel', $object->models)) {
            break;
          }
          module_load_include('inc', 'islandora_manuscript', 'includes/blocks');
          $block['subject'] = t('Container List');
          $block['content'] = islandora_manuscript_container_list($object);
        }
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_preprocess_islandora_object_print().
 */
function islandora_manuscript_preprocess_islandora_object_print(array &$variables) {
  $object = $variables['object'];
  if (in_array('islandora:manuscriptPageCModel', $object->models)) {
    $url = url("islandora/object/{$object->id}", array('absolute' => TRUE));
    $variables['content']['link'] = array(
      '#weight' => -10,
      '#markup' => t('Persistent link: !link', array('!link' => l($url, $url))),
    );
  }
}

/**
 * Implements hook_process_islandora_object_print().
 */
function islandora_manuscript_process_islandora_object_print(array &$variables) {
  $object = $variables['object'];
  if (in_array('islandora:manuscriptPageCModel', $object->models)) {
    $clip = isset($variables['clip']) ? $variables['clip'] : NULL;
    $variables['content']['buttons'] = array(
      '#access' => isset($clip),
      '#prefix' => '<div>',
      '#suffix' => '</div></br>',
      '#weight' => -5,
      'print' => array(
        '#prefix' => '<strong>',
        '#markup' => l(t('Print'), 'javascript:window.print();', array('external' => TRUE)),
        '#suffix' => '</strong>',
        '#weight' => -5,
      ),
      '0' => array(
        '#markup' => ' | ',
        '#weight' => -5,
      ),
      'download_clip' => array(
        '#prefix' => '<strong>',
        '#markup' => l(t('Download Image'), "islandora/object/{$object->id}/download_clip", array(
          'query' => array('clip' => $clip))),
        '#suffix' => '</strong>',
        '#weight' => -5,
      ),
    );
  }
}

/**
 * Implements hook_islandora_paged_content_content_model_registry().
 */
function islandora_manuscript_islandora_paged_content_content_model_registry() {
  return array(
    'islandora:manuscriptCModel' => array(
      'parents' => array(
        'islandora:collectionCModel' => 'isMemberOfCollection',
        'islandora:findingAidCModel' => 'isMemberOf',
      ),
      'children' => array(
        'islandora:manuscriptPageCModel' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xacml_editor_child_query().
 */
function islandora_manuscript_islandora_manuscriptCModel_islandora_xacml_editor_child_query(AbstractObject $object) {
  $pages_query = <<<EOQ
SELECT ?object from <#ri> WHERE
{
  ?object <fedora-rels-ext:isMemberOf> <info:fedora/{$object->id}>
}
EOQ;
  return array(
    'manuscript_pages' => array(
      'type' => 'sparql',
      'query' => $pages_query,
      'description' => t('All pages of this manuscript (existing and new).'),
      'recurse' => TRUE,
    ),
  );
}

/**
 * Implements hook_cron().
 */
function islandora_manuscript_cron() {
  if (variable_get('islandora_manuscript_ead_caching', false)) {
    module_load_include('inc', 'islandora_manuscript', 'includes/ead_html');
    $cachepath = islandora_manuscript_cache_eadhtml_path();
    // Remove expired cachefiles which have themselves expired (probably for objects which don't exist anymore)
    $files = glob($cachepath.'*'.islandora_manuscript_cache_eadhtml_expired_suffix());
    foreach ($files as $file) {
      if (!islandora_manuscript_cachefile_check($file)) {
        unlink($file);
      }
    }
    // Expire cachefiles
    $files = glob($cachepath.'*'.islandora_manuscript_cache_eadhtml_suffix());
    foreach ($files as $file) {
      if (!islandora_manuscript_cachefile_check($file)) {
        copy($file, $file.islandora_manuscript_cache_eadhtml_expired_suffix());
        unlink($file);
      }
    }
    if (module_exists('islandora_solr')) {
      if (!lock_acquire('cron', 360)) {
        watchdog('islandora_solution_pack_manuscript', 'Lost cron lock; aborting cache run.', array(), WATCHDOG_WARNING);
        return;
      } 
      module_load_include('inc', 'islandora_solr', 'includes/utilities');
      // Find any findingAidCModel objects with an EAD datastream
      $qp = new IslandoraSolrQueryProcessor();
      $qp->buildQuery('fedora_datastreams_ms:EAD');
      $qp->solrParams['fq'][] = format_string('!field:("info:fedora/!pid" OR "!pid")', array(
        '!field' => islandora_solr_lesser_escape(variable_get('islandora_solr_content_model_field', 'RELS_EXT_hasModel_uri_ms')),
        '!pid' => 'islandora:findingAidCModel',
      ));
      $qp->solrParams['fl'] = implode(',', array(
        'PID',
      ));
      $qp->executeQuery();
      // queue this object, if a cachefile does not already exist
      $toCache = array();
      $pageIndex = 0;
      $numFound = $qp->islandoraSolrResult['response']['numFound'];
      while ($pageIndex < $numFound - 1) {
        foreach ($qp->islandoraSolrResult['response']['objects'] as $result) {
          $pageIndex++;
          if (!islandora_manuscript_cache_check($result['PID'])) {
            $toCache[$result['PID']] = $result['PID'];
          }
        }
        if ($pageIndex < $numFound - 1) {
          $qp->solrStart = $pageIndex;
          $qp->solrLimit = $numFound;
          $qp->executeQuery();
          $numFound = $qp->islandoraSolrResult['response']['numFound'];
        }
      }
      unset($qp);
      // cache each queued object
      foreach ($toCache as $pid) {
        if (!lock_acquire('cron', 360)) {
          watchdog('islandora_solution_pack_manuscript', 'Lost cron lock; aborting cache creation at !PID .', array('!PID' => $pid), WATCHDOG_WARNING);
          break;
        } 
        $themevars = islandora_manuscript_theme();
        $vars = $themevars['islandora_manuscript_ead_display']['variables'];
        $vars['object'] = islandora_object_load($pid);
        if ($vars['object']) {
          islandora_manuscript_preprocess_ead_display_variables($vars);
          $vars['regenerate_rendered_ead_html'] = true;
          islandora_manuscript_process_ead_display_variables($vars);
          islandora_manuscript_setcache_eadhtml($pid, $vars['rendered_ead_html']);
        } else {
          watchdog('islandora_solution_pack_manuscript', 'Failed to load !PID as indexed by Solr.', array('!PID' => $pid), WATCHDOG_WARNING);
        }
        unset($vars);
      }
    }
  }
}
