<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_manuscript_menu() {
  return array(
    'admin/islandora/solution_pack_config/manuscript' => array(
      'title' => 'Manuscript Solution Pack',
      'description' => 'Configure the Manuscript Solution Pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_manuscript_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_manuscript_islandora_required_objects(IslandoraTuque $connection) {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $module_path = drupal_get_path('module', 'islandora_manuscript');
  // Manuscript Inventory Content Model.
  $manuscript_inventory_content_model = islandora_solution_pack_create_required_object($connection, array(
    'pid' => 'islandora:manuscriptInventoryCModel',
    'label' => 'Manuscript Inventory Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/manuscript_inventory_ds_composite_model.xml",
      ),
    ),
  ));
  // Manuscript Content Model.
  $manuscript_content_model = islandora_solution_pack_create_required_object($connection, array(
    'pid' => 'islandora:manuscriptCModel',
    'label' => 'Manuscript Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/manuscript_ds_composite_model.xml",
      ),
    ),
  ));
  // Manuscript Content Model.
  $transform_content_model = islandora_solution_pack_create_required_object($connection, array(
    'pid' => 'islandora:transformCModel',
    'label' => 'Transform Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/transform_ds_composite_model.xml",
      ),
    ),
  ));
  // Manuscript Inventory Collection.
  $manuscript_collection = islandora_solution_pack_create_required_object($connection, array(
    'pid' => 'islandora:manuscriptCollection',
    'label' => 'Manuscript Collection',
    'model' => 'islandora:collectionCModel',
    'datastreams' => array(
      'TN' => array(
        'file' => "$module_path/images/folder.png",
        'mimetype' => 'image/png',
      ),
      'COLLECTION_POLICY' => array(
        'file' => "$module_path/data/objects/manuscript_collection_policy.xml",
      ),
    ),
  ));
  $manuscript_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Transform Collection.
  $transform_collection = islandora_solution_pack_create_required_object($connection, array(
    'pid' => 'islandora:transformCollection',
    'label' => 'Transform Collection',
    'model' => 'islandora:collectionCModel',
    'datastreams' => array(
      'TN' => array(
        'file' => "$module_path/images/folder.png",
        'mimetype' => 'image/png',
      ),
      'COLLECTION_POLICY' => array(
        'file' => "$module_path/data/objects/transform_collection_policy.xml",
      ),
    ),
  ));
  $transform_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  return array(
    'islandora_manuscript' => array(
      'title' => 'Islandora Manuscript Solution Pack',
      'objects' => array(
        $manuscript_inventory_content_model,
        $manuscript_content_model,
        $transform_content_model,
        $manuscript_collection,
        $transform_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_manuscriptinventorycmodel_islandora_ingest_steps() {
  return array(
    'islandora_manuscript_ead_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_manuscript_ead_upload_form',
      'module' => 'islandora_manuscript',
      'file' => 'includes/ead_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_manuscriptcmodel_islandora_ingest_steps() {
  return array(
    'islandora_manuscript_tei_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_manuscript_tei_upload_form',
      'module' => 'islandora_manuscript',
      'file' => 'includes/tei_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_manuscript_islandora_transformcmodel_islandora_ingest_steps() {
  return array(
    'islandora_manuscript_transform_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_manuscript_transform_upload_form',
      'module' => 'islandora_manuscript',
      'file' => 'includes/transform_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_get_transforms().
 *
 * No default form is defined for EAD, but if someone should add one they can
 * use this transform.
 */
function islandora_manuscript_islandora_xml_form_builder_get_transforms() {
  $module_path = drupal_get_path('module', 'islandora_manuscript');
  return array(
    'ead_to_dc.xsl' => "{$module_path}/data/transforms/ead_to_dc.xsl",
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_manuscript_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_manuscript_mods_form' => array(
      'content_model' => 'islandora:manuscriptCModel',
      'form_name' => 'Manuscript MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_manuscript_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_manuscript');
  return array(
    'Manuscript MODS form' => array(
      'form_file' => "$module_path/data/forms/islandora_manuscript_form_mods.xml",
    ),
  );
}
